### ISSUE TITLE
특정 체커만 Enable하여 실행: -e 옵션

### ISSUE THREAD

**Issue by Min-Ho-Kim** [Min-Ho-Kim/Dexter#3]
Enable only specified checker(s), checkercode1;checkercode2:language:toolname;... eg) -e nullpointer;initializerlist:CPP:cppcheck

 D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>dexter2.bat -u yes.ho -p yes.ho -e nullpointer;initializerlist:CPP:cppcheck

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>java -Xms256m -Xmx786m -XX:MaxPermSize=256m -jar dexter-executor.jar -u yes.ho -p yes.ho -e nullpointer;initializerlist:CPP:cppcheck
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at com.samsung.sec.dexter.executor.cli.DexterCLIOption.setEnabledCheckers(DexterCLIOption.java:207)
        at com.samsung.sec.dexter.executor.cli.DexterCLIOption.setFieldsByCommandLine(DexterCLIOption.java:132)
        at com.samsung.sec.dexter.executor.cli.DexterCLIOption.createCliOptionFromArguments(DexterCLIOption.java:77)
        at com.samsung.sec.dexter.executor.cli.DexterCLIOption.<init>(DexterCLIOption.java:71)
        at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:65)

**Comment by Minjung-Baek** [comment]
@Min-Ho-Kim 
코드 확인해보니 CLI -e 옵션 실행 방법을 수정 해서 테스트 해야 할 것 같습니다. 

▶기존 : ./dexter2.sh -u minjung -p pp253 -e "nullpointer;memleak:CPP:cppcheck" 
▶변경 : ./dexter2.sh -u minjung -p pp253 -e  "memleak:CPP:cppcheck;nullpointer:CPP:cppcheck"


java.lang.ArrayIndexOutOfBoundsException: 0 발생하여 선언할 때 아래와 같이 두었습니다. 
---------------------------------------------------------------------------------------
private String[] enabledCheckerCodes = new String[50];
private String[] enabledCheckerLanguages = new String[10];
private String[] enabledCheckerToolNames = new String[10];

**Comment by Minjung-Baek** [comment]
@Min-Ho-Kim 
코드 확인해보니 CLI -e 옵션 실행 방법을 수정 해서 테스트 해야 할 것 같습니다.

▶기존 : ./dexter2.sh -u minjung -p pp253 -e "nullpointer;memleak:CPP:cppcheck" 
▶변경 : ./dexter2.sh -u minjung -p pp253 -e "memleak:CPP:cppcheck;nullpointer:CPP:cppcheck"

java.lang.ArrayIndexOutOfBoundsException: 0 발생하여 선언할 때 아래와 같이 변경했습니다.

private String[] enabledCheckerCodes = new String[50];
private String[] enabledCheckerLanguages = new String[10];
private String[] enabledCheckerToolNames = new String[10];
