### ISSUE TITLE
서버 없이 독립 실행: -s 옵션

### ISSUE THREAD

**Issue by Min-Ho-Kim** [Min-Ho-Kim/Dexter#5]
Standalone. Run Dexter Analysis without DexterServer. you don't need log in(id & password) eg) -s

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>dexter2.bat -s

D:\dev\dexter\20160811_dexter\cli\dexter-cli_0.10.3_64\bin>java -Xms256m -Xmx786m -XX:MaxPermSize=256m -jar dexter-executor.jar -s
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

===== Starting Dexter Analysis =====

하고 아무것도 일어나지 않았습니다.

**Comment by Minjung-Baek** [comment]
Dexter CLIOption.java: 184

> CommandLineAssert.assertExclusiveMissingMandatoryOptions(cmd, 's', 'u', 'p');

어차피 무조건 아래 조건들에 걸려서 크게 상관없긴 하겠지만, 삭제되어야 할 라인인 것 같습니다. 

>  CommandLineAssert.assertExclusiveOptions(cmd, 's', 'u');
>  CommandLineAssert.assertExclusiveOptions(cmd, 's', 'p');
